import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import '../../db/app_database.dart';
import '../../db/repositories/contacts_repository.dart';
import '../../l10n/app_localizations.dart';
import '../../contacts/avatar_palette.dart';

/// Form to create a new local-only contact or to edit an existing one.
/// No relay traffic is generated by this screen.
class ContactEditorScreen extends StatefulWidget {
  const ContactEditorScreen({super.key, this.contactId});

  /// When null, this is a creation flow. When non-null, the screen edits the
  /// existing Contact row.
  final String? contactId;

  @override
  State<ContactEditorScreen> createState() => _ContactEditorScreenState();
}

class _ContactEditorScreenState extends State<ContactEditorScreen> {
  late final AppDatabase _db = AppDatabase();
  late final ContactsRepository _repo = ContactsRepository(_db);

  final _nameController = TextEditingController();
  final _notesController = TextEditingController();
  String _avatarId = AvatarPalette.idFor(0);
  Contact? _existing;
  bool _loading = true;
  bool _saving = false;

  @override
  void initState() {
    super.initState();
    _bootstrap();
  }

  Future<void> _bootstrap() async {
    if (widget.contactId == null) {
      setState(() => _loading = false);
      return;
    }
    final row = await _repo.get(widget.contactId!);
    if (!mounted) return;
    setState(() {
      _existing = row;
      _nameController.text = row?.displayName ?? '';
      _avatarId = row?.avatarId ?? AvatarPalette.idFor(0);
      _notesController.text = row?.notes ?? '';
      _loading = false;
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  bool get _canSave =>
      _nameController.text.trim().isNotEmpty && _avatarId.isNotEmpty;

  Future<void> _save() async {
    if (!_canSave || _saving) return;
    setState(() => _saving = true);
    final name = _nameController.text.trim();
    final notes = _notesController.text;
    if (_existing == null) {
      final id = 'contact:local:${DateTime.now().toUtc().microsecondsSinceEpoch}';
      await _repo.upsertLocalOnly(
        id: id,
        displayName: name,
        avatarId: _avatarId,
        notes: notes,
      );
    } else {
      await _repo.rename(
        id: _existing!.id,
        displayName: name,
        avatarId: _avatarId,
        notes: notes,
      );
    }
    if (!mounted) return;
    context.pop();
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context);
    final isNew = widget.contactId == null;
    return Scaffold(
      appBar: AppBar(
        title: Text(
          isNew ? l10n.contactsAddLocalOnlyTitle : l10n.contactsEditTitle,
        ),
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : SafeArea(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    TextField(
                      controller: _nameController,
                      decoration: InputDecoration(
                        labelText: l10n.contactsFieldNameLabel,
                        hintText: l10n.contactsFieldNameHint,
                      ),
                      onChanged: (_) => setState(() {}),
                      textInputAction: TextInputAction.next,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      l10n.contactsFieldAvatarLabel,
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(height: 8),
                    Expanded(
                      flex: 2,
                      child: GridView.builder(
                        gridDelegate:
                            const SliverGridDelegateWithFixedCrossAxisCount(
                          crossAxisCount: 5,
                          mainAxisSpacing: 8,
                          crossAxisSpacing: 8,
                        ),
                        itemCount: AvatarPalette.length,
                        itemBuilder: (context, index) {
                          final id = AvatarPalette.idFor(index);
                          final selected = id == _avatarId;
                          return InkWell(
                            onTap: () => setState(() => _avatarId = id),
                            borderRadius: BorderRadius.circular(12),
                            child: DecoratedBox(
                              decoration: BoxDecoration(
                                borderRadius: BorderRadius.circular(12),
                                border: Border.all(
                                  color: selected
                                      ? Theme.of(context).colorScheme.primary
                                      : Theme.of(context).dividerColor,
                                  width: selected ? 2 : 1,
                                ),
                                color: selected
                                    ? Theme.of(context)
                                        .colorScheme
                                        .primaryContainer
                                    : Colors.transparent,
                              ),
                              child: Icon(AvatarPalette.iconAt(index)),
                            ),
                          );
                        },
                      ),
                    ),
                    const SizedBox(height: 16),
                    TextField(
                      controller: _notesController,
                      decoration: InputDecoration(
                        labelText: l10n.contactsFieldNotesLabel,
                        hintText: l10n.contactsFieldNotesHint,
                      ),
                      maxLines: 2,
                    ),
                    const SizedBox(height: 16),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.end,
                      children: [
                        TextButton(
                          onPressed: _saving ? null : () => context.pop(),
                          child: Text(l10n.commonCancel),
                        ),
                        const SizedBox(width: 8),
                        FilledButton(
                          onPressed: _canSave && !_saving ? _save : null,
                          child: Text(l10n.commonSave),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
